<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $siswas = [
            [
                'nis' => '12345',
                'nama' => 'Ahmad Fauzi',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2008-05-15',
                'jenis_kelamin' => 'L',
                'nama_ayah' => 'Budi Santoso',
                'nama_ibu' => 'Siti Aminah',
                'pekerjaan_ayah' => 'Petani',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Merdeka No. 123, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567890',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 1,
            ],
            [
                'nis' => '12346',
                'nama' => 'Siti Nurhaliza',
                'tempat_lahir' => 'Banjarbaru',
                'tanggal_lahir' => '2008-08-20',
                'jenis_kelamin' => 'P',
                'nama_ayah' => 'Hasan Basri',
                'nama_ibu' => 'Fatimah',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Guru',
                'alamat' => 'Jl. Pahlawan No. 45, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567891',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 2,
            ],
            [
                'nis' => '12347',
                'nama' => 'Muhammad Rizki',
                'tempat_lahir' => 'Kandangan',
                'tanggal_lahir' => '2007-12-10',
                'jenis_kelamin' => 'L',
                'nama_ayah' => 'Abdullah',
                'nama_ibu' => 'Zainab',
                'pekerjaan_ayah' => 'Pedagang',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Sudirman No. 67, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567892',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 3,
            ],
            [
                'nis' => '12348',
                'nama' => 'Dewi Sartika',
                'tempat_lahir' => 'Batulicin',
                'tanggal_lahir' => '2008-03-25',
                'jenis_kelamin' => 'P',
                'nama_ayah' => 'Joko Widodo',
                'nama_ibu' => 'Iriana',
                'pekerjaan_ayah' => 'PNS',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Gatot Subroto No. 89, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567893',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 1,
            ],
            [
                'nis' => '12349',
                'nama' => 'Andi Pratama',
                'tempat_lahir' => 'Martapura',
                'tanggal_lahir' => '2007-09-05',
                'jenis_kelamin' => 'L',
                'nama_ayah' => 'Sukirman',
                'nama_ibu' => 'Murni',
                'pekerjaan_ayah' => 'Nelayan',
                'pekerjaan_ibu' => 'Pedagang',
                'alamat' => 'Jl. Ahmad Yani No. 234, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567894',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 2,
            ],
            [
                'nis' => '12350',
                'nama' => 'Rina Kartika',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2008-11-30',
                'jenis_kelamin' => 'P',
                'nama_ayah' => 'Bambang',
                'nama_ibu' => 'Susanti',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pekerjaan_ibu' => 'Guru',
                'alamat' => 'Jl. Diponegoro No. 56, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567895',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 3,
            ],
            [
                'nis' => '12351',
                'nama' => 'Fajar Nugraha',
                'tempat_lahir' => 'Banjarbaru',
                'tanggal_lahir' => '2007-07-18',
                'jenis_kelamin' => 'L',
                'nama_ayah' => 'Herman',
                'nama_ibu' => 'Linda',
                'pekerjaan_ayah' => 'Petani',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Pangeran Antasari No. 78, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567896',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 1,
            ],
            [
                'nis' => '12352',
                'nama' => 'Putri Ayu',
                'tempat_lahir' => 'Kandangan',
                'tanggal_lahir' => '2008-02-14',
                'jenis_kelamin' => 'P',
                'nama_ayah' => 'Dedi',
                'nama_ibu' => 'Rina',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'alamat' => 'Jl. Ki Hajar Dewantara No. 90, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567897',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 2,
            ],
            [
                'nis' => '12353',
                'nama' => 'Aldi Firmansyah',
                'tempat_lahir' => 'Batulicin',
                'tanggal_lahir' => '2007-04-22',
                'jenis_kelamin' => 'L',
                'nama_ayah' => 'Rudi',
                'nama_ibu' => 'Dewi',
                'pekerjaan_ayah' => 'PNS',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Siliwangi No. 12, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567898',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 3,
            ],
            [
                'nis' => '12354',
                'nama' => 'Maya Sari',
                'tempat_lahir' => 'Martapura',
                'tanggal_lahir' => '2008-06-08',
                'jenis_kelamin' => 'P',
                'nama_ayah' => 'Agus',
                'nama_ibu' => 'Ani',
                'pekerjaan_ayah' => 'Pedagang',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Hasanuddin No. 34, Simpang Empat, Tanah Bumbu',
                'telp' => '081234567899',
                'tanggal_masuk' => '2023-07-15',
                'jurusan_id' => 1,
            ],
        ];

        foreach ($siswas as $siswa) {
            Siswa::create($siswa);
        }
    }
}